### ISSUE TITLE
Wan't run on Win10

### ISSUE THREAD

**Issue by jul-star** [constverum/Quantdom#1]
c:\Program Files (x86)\Python\Lib\site-packages>quantdom
Traceback (most recent call last):
  File "c:\program files (x86)\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python\Scripts\quantdom.exe\__main__.py", line 5, in <module>
  File "c:\program files (x86)\python\lib\site-packages\quantdom\__init__.py", line 29, in <module>
    from .ui import *  # noqa
  File "c:\program files (x86)\python\lib\site-packages\quantdom\ui.py", line 10, in <module>
    from .lib import (  # noqa
ModuleNotFoundError: No module named 'quantdom.lib'

**Comment by TigerSang** [comment]
Same problem, can't install under Win10, and the .exe file can't properly run on Win10, at least, it doesn't look the same as the one shown on this webpage.

**Comment by maxlz** [comment]
Same problem in Win7 SP1

**Comment by anarchy89** [comment]
im getting the same error on mac os and windows 10, it says that there is no module named quantdom.lib after installation.

**Comment by JafferWilson** [comment]
Try to use this for windows: https://github.com/constverum/Quantdom/releases/download/v0.1a1/quantdom_0.1a1.exe

**Comment by anarchy89** [comment]
hi, what about mac? why cant i load custom price info

**Comment by constverum** [comment]
@anarchy89 

> what about mac?

Please check the [releases page](https://github.com/constverum/Quantdom/releases). For mac you can download it by [link](https://github.com/constverum/Quantdom/releases/download/v0.1a1/quantdom_0.1a1.dmg).

> why cant i load custom price info

What are you mean? Do you want to import your custom data (quotes), for example from other markets or at other time intervals (tick/minute)? I would also like this =), but _for now_ I couldn't find a simple and convenient way for this. There is simply no such data in *open/free* access, which means that everyone will have to import quotes available to him in manual mode and there is a problem - I just do not know in what format and how this data will be organized, therefore it's difficult to implement (and that at the same time it was convenient and easy for a user).
But if anyone has any ideas about an open source of data for the tool (at least minutes in a few years) - we can discuss them here.

**Comment by JafferWilson** [comment]
@anarchy89  I gues you have not read the read.me file properly. This is very bad that you are raising question without knowing the repository completely. Here have a look at the link: https://github.com/constverum/Quantdom/releases/download/v0.1a1/quantdom_0.1a1.dmg

**Comment by constverum** [comment]
Fixed in v0.1
