### ISSUE TITLE
Custom data menu grayed out

### ISSUE THREAD

**Issue by ppop** [constverum/Quantdom#5]
I've installed Quantdom from source and from binaries (for Mac).

I can run backtests using Shares/Futures/ETFs data, but I cannot import any custom data as the menu is grayed out.

I've checked that the requirements are correctly installed (especially PyQt5).

<img width="794" alt="screen shot 2018-08-04 at 09 58 31" src="https://user-images.githubusercontent.com/1155761/43673521-278c4a44-97cd-11e8-9d3f-8f3ffed9ed05.png">

**Comment by constverum** [comment]
Paul,
> but I cannot import any custom data as the menu is grayed out.
Please check this [comment](https://github.com/constverum/Quantdom/issues/1#issuecomment-374874174).

**Comment by ppop** [comment]
That's a bummer!
